apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: words-db
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: words-db
    spec:
      containers:
        - name: words-db
          image: adamsandor83/easykube-db:VERSION
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
            limits:
              cpu: 1
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 27017
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 27017
            periodSeconds: 3
            timeoutSeconds: 30
          ports:
            - containerPort: 27017
          volumeMounts:
              - name: word-list
                mountPath: /words
      volumes:
        - name: word-list
          persistentVolumeClaim:
            claimName: words-db-claim
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: words-db-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "standard"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
