apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: container-solutions/easykube-frontend:VERSION
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 1
            memory: 400Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          periodSeconds: 3
          timeoutSeconds: 30
        env:
          - name: BACKEND_URL
            value: http://backend
        ports:
        - containerPort: 8080
