apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 10%
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: container-solutions/easykube-backend:VERSION
          resources:
            requests:
              cpu: 100m
              memory: 150Mi
            limits:
              cpu: 1
              memory: 400Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 3
            timeoutSeconds: 30
          ports:
            - containerPort: 8080
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DB_PASSWORD
